### ISSUE TITLE
bin/console not scaffolded in correct path ?

### ISSUE THREAD

**Issue by mickaelperrin** [mautic/recommended-project#7] opened 2021-11-03 11:55 UTC
Hi,

I try to install Mautic using composer as I do with any other open source project.

I experience some issues, one of them is that the bin/console file is scaffolded in the parent directory of `docroot`.

This file requires `__DIR__.'/../app/autoload.php';` which can't be found.

Not sure how to resolve this properly.

**Comment by nickveenhof** [comment] 2021-11-08 20:37
Hmm. Curious. Can you post steps to reproduce?

**Comment by rjocoleman** [comment] 2021-11-09 02:09
I came across the same issue:

Here are steps to reproduce:

```shell
$ composer create-project mautic/recommended-project:4.x-dev some-dir --no-interaction
$ cd some-dir
$ chmod +x bin/console
$ bin/console
# PHP Warning:  require_once(/path/to/some-dir/bin/../app/autoload.php): failed to open stream: No such file or directory in /path/to/some-dir/bin/console on line 21
# PHP Fatal error:  require_once(): Failed opening required '/path/to/some-dir/bin/../app/autoload.php' (include_path='.:') in /path/to/some-dir/bin/console on line 21
```


My workaround (unsure if this is best practice but it works for me):

Added a `post-mautic-scaffold-cmd` script in `composer.json`:
```json
  "name": "my/project",
  ...
  "scripts": {
    "post-mautic-scaffold-cmd": [
      "patch -p1 < patches/console.patch"
    ]
  }
```

`patches/console.patch`:
```diff
diff --git a/bin/console b/bin/console
index 65e7ded..a5cb68d 100755
--- a/bin/console
+++ b/bin/console
@@ -16,10 +16,10 @@ if (function_exists('set_time_limit')) {

 defined('IN_MAUTIC_CONSOLE') or define('IN_MAUTIC_CONSOLE', 1);

-define('MAUTIC_ROOT_DIR', realpath(__DIR__.'/..'));
+define('MAUTIC_ROOT_DIR', realpath(__DIR__.'/../docroot'));

-require_once __DIR__.'/../app/autoload.php';
-require_once __DIR__.'/../app/AppKernel.php';
+require_once __DIR__.'/../docroot/autoload.php';
+require_once __DIR__.'/../docroot/app/AppKernel.php';

 use Mautic\CoreBundle\Console\Output\ConsoleDatetimeOutput;
 use Symfony\Bundle\FrameworkBundle\Console\Application;
```

Each time the scaffold is done my `bin/console` is patched with working paths. I noticed that despite there being a file at `docroot/app/autoload.php` it does not had the correct paths set up for this usage. I haven't dug in too deeply to be totally certain I'm using the correct autoload.

**Comment by nickveenhof** [comment] 2021-11-09 20:28
I'm going to investigate and get back to you. I think you might need this PR patch

https://github.com/mautic/mautic/pull/10297

Please review and see if we can push this forward :)

**Comment by rjocoleman** [comment] 2021-11-09 23:01
thanks @nickveenhof 

I'm not having luck with the patch from mautic/mautic#10297

this is the minimum patch I need (due to `docroot` from mautic/recommended-project):

```patch
diff --git a/bin/console b/bin/console
old mode 100644
new mode 100755
index 8c6243f..de0b6e4
--- a/bin/console
+++ b/bin/console
@@ -18,8 +18,7 @@ defined('IN_MAUTIC_CONSOLE') or define('IN_MAUTIC_CONSOLE', 1);
 
 define('MAUTIC_ROOT_DIR', realpath(__DIR__.'/..'));
 
-require_once __DIR__.'/../autoload.php';
-require_once __DIR__.'/../app/AppKernel.php';
+require_once __DIR__.'/../docroot/autoload.php';
 
 use Mautic\CoreBundle\Console\Output\ConsoleDatetimeOutput;
 use Symfony\Bundle\FrameworkBundle\Console\Application;
diff --git a/docroot/app/assets/scaffold/files/console b/docroot/app/assets/scaffold/files/console
index 8c6243f..de0b6e4 100755
--- a/docroot/app/assets/scaffold/files/console
+++ b/docroot/app/assets/scaffold/files/console
@@ -18,8 +18,7 @@ defined('IN_MAUTIC_CONSOLE') or define('IN_MAUTIC_CONSOLE', 1);
 
 define('MAUTIC_ROOT_DIR', realpath(__DIR__.'/..'));
 
-require_once __DIR__.'/../autoload.php';
-require_once __DIR__.'/../app/AppKernel.php';
+require_once __DIR__.'/../docroot/autoload.php';
 
 use Mautic\CoreBundle\Console\Output\ConsoleDatetimeOutput;
 use Symfony\Bundle\FrameworkBundle\Console\Application;

```
I am unsure about `MAUTIC_ROOT_DIR` setting.

(my patch is also setting `chmod +x bin/console` as that's not done as part of the scaffold)

Note for applying this workaround if anyone needs it:
I could not work out how to get `composer-patches` to apply to `mautic/core-lib` package so I am using a composer post script.

It's saved as `patches/console.patch` in my project and the following is added to composer.json:
```json
  "scripts": {
    "post-mautic-scaffold-cmd": [
      "patch --no-backup-if-mismatch -p1 --forward -r - < patches/console.patch || true"
    ]
  }
```
(so that this can be used as part of a CI/CD or otherwise unattended, the patch command arguments are set to avoid creating `.orig` backup files, skip the patch if it's already applied (as is the case with default scaffold setup where the files are commited, skip `.rej` files once skipped. Always exit with a `true` as if it's already applied `patch` exit status is non-zero and that will abort the composer run.

**Comment by mollux** [comment] 2021-11-10 14:09
@rjocoleman The patch is indeed a bit tricky, as it is meant for the mautic/mautic project, and composer is pulling the mautic/core-lib project.

Once mautic/mautic#10297 is merged and released, this problem will go away.
In the meantime I use 1 specific file (the "source" file in the scaffold folder) from that patch in my composer.json

```
...
"extra": {
  "patches": {
    "mautic/core-lib": {
       "Allow console to leverage the generic autoloader regardless of the location (partial of https://github.com/mautic/mautic/pull/10297)": "https://github.com/mautic/mautic/commit/61b125364464dbd1b52285e7870e9fe4e45492a7.diff"
    }
  }
}
...
```

**Comment by rjocoleman** [comment] 2021-11-11 11:01
the problem I've got with the patch in mautic/mautic#10297 is:

* mautic/recommended-project gives me a project looking like this:

```shell
$ tree -L 2
.
├── app
├── bin
│   └── console
├── composer.json
├── composer.lock
├── docroot
│   ├── app
│   ├── autoload.php
│   ├── favicon.ico
│   ├── index_dev.php
│   ├── index.php
│   ├── media
│   ├── offline.php
│   ├── plugins
│   ├── robots.txt
│   ├── themes
│   ├── translations
│   └── upgrade.php
├── Gruntfile.js
├── package.json
├── package-lock.json
├── README.md
└── vendor
    ├── autoload.php
    ├── <snip>
    
79 directories, 15 files
```

i.e. in my root (`some-dir`) I have `./bin/console` and then I have `./docroot`

mautic/mautic#10297 wants `autoload.php` to exist at `__DIR__.'/../autoload.php'`.

Relative to `./bin` this means it's looking for `./autoload.php`. I don't have an `autoload.php` in my project root. 

there is an autoload at `./docroot/autoload.php` and `./vendor/autoload.php` - both of these work.

I understand that `docroot` is supposed to be configurable so hardcoding it into `bin/console` require path is not ideal. 

Perhaps `/vendor/autoload.php` could be used instead?

I've used the default configuration of mautic/recommended-project from the README, (`composer create-project mautic/recommended-project:4.x-dev some-dir --no-interaction`)

What am I missing here? 

Steps to reproduce:

```shell
$ composer create-project mautic/recommended-project:4.x-dev some-dir --no-interaction
$ cd some-dir
$ composer require cweagans/composer-patches:~1.0
# add composer patch to `extra` e.g. with jq and tee (or by hand)
$ cat composer.json | jq '.extra.patches |= {"mautic/core-lib":{"Allow console to leverage the generic autoloader regardless of the location (partial of https://github.com/mautic/mautic/pull/10297)":"https://github.com/mautic/mautic/commit/61b125364464dbd1b52285e7870e9fe4e45492a7.diff"}}' | tee composer.json 
$ composer install
$ php bin/console
# PHP Warning:  require_once(/path/to/some-dir/bin/../autoload.php): failed to open stream: No such file or directory in /path/to/some-dir/bin/console on line 21
```

**Comment by tijsdeboeck** [comment] 2021-11-27 14:28
I can confirm this, had the exact same issue. Patching it using composer-patches does not solve this issue, since the scaffolding happens after the patches are applied. I'm working arround it in the same way @rjocoleman suggested in his [comment](https://github.com/mautic/recommended-project/issues/7#issuecomment-964622931):

```
"scripts": {
        "post-mautic-scaffold-cmd": [
            "patch -p1 < patches/console-correct-autoload-path.patch"
        ]
    },
```

**Comment by davidspiola** [comment] 2022-02-14 21:33
This is still a thing, isn't it? I wonder what the best solution would be. Moving away from 'docroot' feels like going into the wrong direction.

**Comment by RCheesley** [comment] 2022-03-29 14:14
Yes it is still a thing - the problem is that the way proposed in https://github.com/mautic/mautic/pull/10297 is not backwards compatible - this means in the current state we could not merge it unless we wait until the 5.0 release (slated for the end of September) or we make another major release out-of-sequence which is no small feat, and not something that we really want to do if we can possibly avoid it.

I have [asked if there is any way this could be achieved in a non-BC way](https://github.com/mautic/mautic/pull/10297#issuecomment-1073932178) as it is blocking a lot of things for people - if anyone has any thoughts please do jump in on the issue!

**Comment by Moongazer** [comment] 2023-05-06 10:56
I think this issue is solved, at least we haven't had any prolems with this in the recent versions of 4.4.5+ using composer installation with `mautic/recommended-project`.

**Closed as completed** 2023-05-09 13:50 UTC
